### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#22]
Link/Copy http://www.brainhack.org/code-of-conduct.html and add two local contacts.

**Comment by cclairec** [comment]
Where should we add it? in the "more section" ?

**Comment by cmaumet** [comment]
We could add a section for it so that it is more easily accessible.

**Comment by cclairec** [comment]
Ok, I will do that dotay. But should I just put the like to the brainhack code of conduct, or should I copy it on the new section?

**Comment by cmaumet** [comment]
Thank you @cclairec! Slowly for the slow responsivness! The update you just merged (#23) looks good to me. 

Would you be okay to be one of the two contacts? I am happy to be the second one.

**Comment by cclairec** [comment]
I'm ok with that! Will do the change.

**Comment by cmaumet** [comment]
Thanks!

**Comment by ocommowi** [comment]
C'est fait non ? On peut fermer ?

**Comment by cmaumet** [comment]
Je crois qu'il manque encore les 2 emails en contacts?

**Comment by cclairec** [comment]
Ha ouais, c'est vrai. Je mets Camille et moi donc.

**Comment by cmaumet** [comment]
Merci !
