### ISSUE TITLE
Besoins info: igrida ?

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#39]

**Comment by cmaumet** [comment]
Le projet de Francesca necessite potentiellement d'utiliser igrida. Elle peut fonctionner sans mais cela vaudrait quand même le coup de vérifier si igrida est accessible pour les extérieurs. Est-ce que qqun de vous à de l'expérience avec igrida et en sait plus ?

**Comment by ocommowi** [comment]
Francesca a contacté Guillermo. En substance : 
- machines reservees pour brainhack -> done
- connexion exterieur a igrida -> faisable mais au cas par cas donc penible a priori

**Comment by cmaumet** [comment]
Merci !! Du coup on part sur l'idée qu'igrida ne sera accessible qu'aux internes en créant des binomes travaillant sur la même machine si besoin ?
