### ISSUE TITLE
Nouvelle image ?

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#4]
Pour se différencier de Brainhack Warwick 2017, si on changeait la photo d'en tête ? L'an dernier on l'avait trouvé sur Flicker si je me rappelle bien. Vous en pensez quoi ? Des idées ?

**Comment by cclairec** [comment]
Est ce que cette image irait? 
![brainhack2018](https://user-images.githubusercontent.com/15160042/37034302-297f2830-2149-11e8-8aa9-304801d4de2e.png)

**Comment by cmaumet** [comment]
J'<3  

Est-ce que la licence est ok ?

**Comment by cmaumet** [comment]
Il y a aussi des images sympas avec des neurones, par exemple:
 - [Mouse Embryo Cerebellum](https://www.flickr.com/photos/nihgov/30698034186/in/photolist-NLFs4u-T1LAaZ-9ptvW2-Xwm5bP-UGPVtf-nikcAk-ijTCS4-22Ngnoi-Suru1V-jBfgGf-nRx5aU-nigEST-gkFbdQ-rduxS-23Ufbbc-K1AuQc-5qRjQ-gEVDf-T4qpE4-dKCa5-9851h4-SusNAD-bpKjeG-9GmHuL-T9gyEy-SzvPX8-cBRrrf-fUN632-7aC7FH-21WArAK-ngnaji-XBm8V9-TEFN3o-SWz9r2-GS5nUB-xfVcNz-TJ9CQn-y8iDWp-TJ9FhM-wLemmm-aXCGL4-mibGPY-Sx6pNs-oS3xmN-a9MrEM-8tFXEP-8z9LJJ-e4Ar1Q-pntPcb-5oKMSo)

NIH photo gallery: https://www.flickr.com/photos/nihgov/

**Comment by cclairec** [comment]
Pour les 2 que j'ai posté au dessus, on peut toujours leurs demander les droits, on sait jamais!
Je regarde les autres.
Sinon on peut filtrer par "libre de droits" les images?

**Comment by cmaumet** [comment]
> Sinon on peut filtrer par "libre de droits" les images?

Ici : https://www.flickr.com/creativecommons/ ?

**Comment by cclairec** [comment]
Bon, je tente un truc fait maison, avec que du libre de droit.

**Comment by cclairec** [comment]
Bon, voilà un essai. Mais j'ai l'impression qu'une image rectangulaire serait mieux. Quelle est la taille que l'image doit faire pour le site?

![brainhack2018_2](https://user-images.githubusercontent.com/15160042/37041119-b3b9bcc4-215b-11e8-9f17-9b401684b0d4.png)

**Comment by cmaumet** [comment]
The image to replace is: https://github.com/Inria-Visages/brainhackrennes-2018/blob/master/img/brainhack_webbanner.jpg

**Comment by cmaumet** [comment]
I've added your image to the website: what do you think?

**Comment by cmaumet** [comment]
![screen shot 2018-03-06 at 16 49 40](https://user-images.githubusercontent.com/5374264/37042288-6a78b986-215e-11e8-882f-7e2cb29b7a97.png)

**Comment by cmaumet** [comment]
Sinon:

![screen shot 2018-03-06 at 16 51 05](https://user-images.githubusercontent.com/5374264/37042372-994fba5c-215e-11e8-9c46-c51d544b9246.png)

**Comment by cmaumet** [comment]
![screen shot 2018-03-06 at 16 52 33](https://user-images.githubusercontent.com/5374264/37042469-cab04bd4-215e-11e8-915e-f92b8fc66924.png)

**Comment by cmaumet** [comment]
![screen shot 2018-03-06 at 16 53 33](https://user-images.githubusercontent.com/5374264/37042588-079fa396-215f-11e8-98ee-00e64e8a6898.png)

**Comment by cmaumet** [comment]
![screen shot 2018-03-06 at 16 55 20](https://user-images.githubusercontent.com/5374264/37042654-2e6c94f2-215f-11e8-8249-d613a208c504.png)

**Comment by cclairec** [comment]
Elle est marrante l'avant dernière, on dirait des paquerettes! Par contre je pense qu'il faut mettre un cerveau, sinon ils vont penser qu'on fait de la bio moleculaire... ! 

Bon, en tous cas il faut une image plus lissée. Je lisse celle que j'ai.

**Comment by jcoloigner** [comment]
d'accord avec Claire. Il faut mettre un cerveau

**Comment by cclairec** [comment]
Voici des images plus lisses. (pour le vert au niveau des écritures, je vois ca demain).

**Comment by cclairec** [comment]
![brainhack2018_3](https://user-images.githubusercontent.com/15160042/37043640-71dac1da-2161-11e8-9ff2-342134b9b751.png)
![brainhack2018_4](https://user-images.githubusercontent.com/15160042/37043645-74f9561a-2161-11e8-98ce-f403b4d4be9f.png)

**Comment by cclairec** [comment]
J'ai mis une image plus simple sur le site, qui va avec la couleur du thème. Vous en dites quoi?

En tous cas il faut retirer le
"Image credit: "Open Mind" by Christian Weidinger, Flickr"
