### ISSUE TITLE
Fermeture des inscriptions : prévenir sigima

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#43]

**Comment by cclairec** [comment]
Pour prévenir Sigma, il faut envoyer un mail à la liste sigma, ou il faut passer par un tiers ?

**Comment by cmaumet** [comment]
Il faut envoyer un mail à la liste et ensuite je dois pouvoir l'accepter car je suis dans les modérateurs. Tu veux t'en occuper ?

**Comment by cclairec** [comment]
Ok. Je peux envoyer le même mail que j'ai envoyé à VISAGES de toutes facons, non?

**Comment by cmaumet** [comment]
Oui ce serait parfait !
