### ISSUE TITLE
Fermeture des inscriptions : prévenir Visages

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#44]

**Comment by cclairec** [comment]
J'envoie ce message, si pas de contre-indications:

Bonjour à tous,

Les inscriptions pour Brainhack ferment le 16 avril, soit bientôt.

Petit rappels:
- L'inscription n'engage pas à la soumission d'un projet.
- Si vous voulez proposer un projet, vous pouvez nous l'envoyer au format suivant:

    Name: 16 (32) character name of the project or resource (anything longer might be truncated).
    Description: 200 (400) character description of the project, anything longer will be truncated
    Project logo: preferably a 222 x 180 (466 x 180) 72 dpi image in png format

- Si vous ne voulez pas proposer de projet, pour pourrez rejoindre l'un des projets proposés. Ils sont mis en ligne au fur et à mesure sur le site de brainhack: https://brainhack.irisa.fr/

Très bonne fin de semaine,
Claire for brainhack.

**Comment by cmaumet** [comment]
+1. Peut-être changer "name" en "title" ? Nos premiers projets ont des titres plutot long. Merci !!

**Comment by cclairec** [comment]
Ha flute, j'avais pas vu la fin de ton message. J'ai envoyé sans le nombre de places restantes.

**Comment by cmaumet** [comment]
C'est de ma faute : j'ai édité après coup ;)
