### ISSUE TITLE
Mise en ligne des projets

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#47]

**Comment by cmaumet** [comment]
- [ ] Quentin
 - [ ] Francesca

**Comment by cclairec** [comment]
Name: mne-bids
URL: https://mne-tools.github.io/mne-bids/
Description:
MNE BIDS is a python package to automatically converting existing
files into BIDS compatible datasets.
Contact information: mainakjas@gmail.com
Project logo: https://github.com/mne-tools/mne-python/blob/master/doc/_static/mne_logo.png

- [ ] Mainak Jas
