### ISSUE TITLE
Domain in inria or irisa

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#5]
Est-ce que tu sais si on a la possibilité d'avoir un sous nom de domaine avec l'Inria ? On peut garder l'hébergement GitHub mais si on peut avoir une adresse avec inria.fr ce serait encore mieux :)

**Comment by cmaumet** [comment]
(work-in-progress by @ocommowi)

**Comment by ocommowi** [comment]
C'est fait. On a eu un "reverse proxy http" (aucune idee de ce que c'est) sur brainhack.irisa.fr
