### ISSUE TITLE
Trouver qqun pour porter un projet de diffusion

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#51]

**Comment by ocommowi** [comment]
Manu ? Avec Raphael ils pourraient faire un truc. Ils avaient pas l'air fermés a l'idee ce matin

**Comment by cmaumet** [comment]
Oui, bonne idée. Es-tu d'accord pour t'occuper de voir avec lui si il veut bien donner une petite idée de projet pour le site web ?

**Comment by ocommowi** [comment]
Manu a pas l'air chaud et personnellement j'en ai deja deux des projets. Ou alors j'en remplace un
