### ISSUE TITLE
Essayer d'avoir des projets venant de personnes extérieures à Visages

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#53]

**Comment by ocommowi** [comment]
Je peux prendre la liste et envoyer un mail aux participants inscrits actuellement pour leur demander la meme chose que l'on a sur le site

**Comment by cmaumet** [comment]
Bonne idée ! En sachant qu'il y a des extérieurs auxquels on n'a pas parlé directement donc il faudrait peut-être décrire un peu ce qu'on veut dire par projet, i.e. c'est très large, projet de dev, discussion de groupe, auto-formation sur un dev/soft, etc.

**Comment by ocommowi** [comment]
C'est un peu la meme chose que #54 non ? Je peux fermer ?

**Comment by cmaumet** [comment]
Oui j'espère :) Mais on peut peut-être attendre de voir si on a des réponses suite à #54. Si ce n'est pas le cas on pourrait aussi tenter des mails plus cliblés à partir des réponses au questionnaire. Donc je dirais, attendons un peu, ça te va ?

**Comment by ocommowi** [comment]
Ok ca marche, no problem

**Comment by ocommowi** [comment]
On en a un, deux autres contactés dans les nouveaux inscrits
