### ISSUE TITLE
Trouver qqun pour porter un projet sans developement logiciel (ex: discussion autour d'une thématique)

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#58]

**Comment by MathisFleury** [comment]
Développement d'une interface d'aide au diagnostic pour les radiologues. Ex: Lorsqu'il voit telle ou telle image de T1 ou T2, le logiciel lui dirait la probabilité que ce soit cette pathologie ou non. Ensuite le radiologue pourrait en fonction du patient, de ses hypothèses et de ses probabilités donner son diagnostic. Cependant dans un premier temps il serait intéressant de développer une plateforme regroupant l'ensemble des pathologies neurologique ou non et les images associées. On pourrait citer l'exemple d'IMAIOS.

PS: Je sais que ce n'est pas non plus un projet non logiciel totalement mais on s'en rapproche plus :)

**Comment by ocommowi** [comment]
Y a le projet d'Elise que j'ai rajoute vendredi, ca semble bien etre une discussion sur l'irmf sans dev logiciel

**Comment by cmaumet** [comment]
Oui. Du coup on peut fermer, ça nous en fait déjà un :) Et Mathis si tu veux, tu peux aussi ajouter le tien.

**Comment by cclairec** [comment]
Il faudrait peut être faire monter ce projet en 2nd ou 3ieme place dans la liste des projets, pour qu'il soit visible dés le début? La vue de tous les autres projets nécessitant du code pourrait décourager des non-codeurs de venir, non?

**Comment by cmaumet** [comment]
Peut-être qu'on pourrait aussi en profiter pour remonter le "your project!" en première place (plutot qu'en dernière atuellement) ?

**Comment by cclairec** [comment]
#68 merged !
