### ISSUE TITLE
Create and add calendar

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#6]

**Comment by ocommowi** [comment]
It exists, hosted on visagesweb@gmail.com. I’ll fill it with a default schedule soon

**Comment by cmaumet** [comment]
Hi @ocommowi! Thanks!

Currently on the website, I see a white space where the calendar should be while I was expecting to have an empty calendar. Is this as expected? If not, do you have the same behavior on your machine?

Screenshot:
![screen shot 2018-03-02 at 17 23 25](https://user-images.githubusercontent.com/5374264/36909504-70be4cc0-1e3e-11e8-9d55-5ce12d5ffb40.png)

**Comment by ocommowi** [comment]
I had not opened the calendar to the outside world. Is it working now ?

**Comment by cmaumet** [comment]
Thanks! Yes, now I can see the empty calendar:

![screen shot 2018-03-05 at 09 00 04](https://user-images.githubusercontent.com/5374264/36963481-a8f6bb92-2053-11e8-924b-b198f635b677.png)

Let's discuss the schedule in our meeting today and then we can fill the calendar.

**Comment by ocommowi** [comment]
Done
