### ISSUE TITLE
Demander a edith pub des talks sur ecran cafet

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#82]
(Après fermeture des inscriptions le 16 avril).

**Comment by MathisFleury** [comment]
Contact avec edith effectué: "A priori pas de soucis pour diffuser via les écrans video - on finalise à notre prochaine réunion le 17."

**Comment by cmaumet** [comment]
Reparlé avec édith en réunion, on diffusera à la cafet "Brainhack, en ce moment" le 25 et le 26 avril. Donc c'est tout bon !
