### ISSUE TITLE
Réfléchir aux badges: ajouter l'image du site comme logo? Une icone pour signaler les orgas et une autre pour les personnes à contacter lié au code of conduct

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#94]
Je ne sais pas si c'est possible mais que pensez-vous de:
 - Une icone pour signaler les orgas
 - une icone pour les personnes à contacter lié au code of conduct
 - une icone pour signaler les personnes locales à l'Inria

L'idée serait de permettre plus facilement aux participants de repérer certaines personnes. Par exemple les locaux peuvent répondre à toutes sortes de questions (e.g. où trouver les toilettes ;) )

**Comment by cclairec** [comment]
Pour l'image, j'en ai envoyé une a Edith apres la reunion.
