### ISSUE TITLE
Campagne de mails pour les participants : une semaine avant pour infos pratiques

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes#99]
- Info pratique comment rejoindre IRISA (copie site web)
 - Rappel programme
 - ~si besoin : piece id !~

**Comment by cmaumet** [comment]
- heure de début : 9h / croissants

**Comment by ocommowi** [comment]
Deuxieme mail a faire :
- attestation potentielle pour formation pour les etudiants
- venez avec vos machines
- wifi = eduroam -> prevenir si besoin d'autre chose

**Comment by ocommowi** [comment]
Done
